@echo off
rem Generated by JetBrains Toolbox 3.0.1.59888 at 2025-10-30T01:09:33

set waitarg=
set intellij_args=

:next
set "passwait="
if "%~1"=="--wait" set passwait=1
if "%~1"=="-w" set passwait=1
if defined passwait (set waitarg=/wait)
if not "%~1"=="" (
  if defined passwait (set "intellij_args=%intellij_args%--wait ") else (set "intellij_args=%intellij_args%%1 ")
  shift
  goto next
)

start "" %waitarg% "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2025.2.3\bin\idea64.exe" %intellij_args%